### ISSUE TITLE
mobiscroll.zepto.js is lost in the project

### ISSUE THREAD

**Issue by liyj144** [Monster-L/datepicker.mobile#1]
Hi, Felix. Yesterday, i search for datepicker used in mobile, and found this project. But my project is based on frozenui and zepto. I found you have  a demo named **index-zepto.html**.I think this is built for zepto. But this library **mobiscroll.zepto.js** is not found in the project. Hopes you can add it.Thanks.

**Comment by Monster-L** [comment]
already add it

**Comment by liyj144** [comment]
Thanks
